import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";

import Icons from "../components/Icons";
import Heading from "../sections/Heading";
import PoolProgress from "../sections/PoolProgress";
import Stats from "../sections/Stats";
import CTA from "../sections/CTA";
import NeonIcon from "../components/NeonIcon/NeonIcon";

const Home: NextPage = () => {
  return (
    <div
      style={{ height: "100vh", width: "100vw", backgroundColor: "#131212" }}
    >
      <Head>
        <title>Kwenta Aelin Raise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledMain>
        <Icons />
        <NeonIcon />
        <Heading />
        <Stats />
        <PoolProgress />
        <CTA />
      </StyledMain>
    </div>
  );
};

const StyledMain = styled.main`
  margin: 0 auto;
  max-width: 810px;
  height: 100%;
  width: 100%;
  padding: 0 20px;

  display: flex;
  flex-direction: column;
  align-items: center;
`;

export default Home;
