import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";

import Heading from "../sections/Heading";
import PoolProgress from "../sections/PoolProgress";
import Stats from "../sections/Stats";
import CTA from "../sections/CTA";
import NeonIcon from "../components/NeonIcon/NeonIcon";
import TopBar from "../sections/TopBar/TopBar";

const Home: NextPage = () => {
  return (
    <PageContainer>
      <Head>
        <title>Kwenta Aelin Raise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBar />

      <StyledMain>
        <NeonIcon />
        <Heading />
        <Stats />
        <PoolProgress />
        <CTA />
      </StyledMain>
    </PageContainer>
  );
};

const PageContainer = styled.div`
  height: 100vh;
  width: 100vw;
  background-color: #131212;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;

  @media only screen and (max-width: 480px) {
    .topBar {
      display: none;
    }
  }
`;

const StyledMain = styled.main`
  margin: 0 auto;
  max-width: 600px;
  height: 100%;
  width: 100%;
  padding: 0 20px;

  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

export default Home;
