import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Icons from "../components/Icon/Icons";
import usePoolCreatedQuery from "../queries/usePoolCreatedQuery";
import { parsePool } from "../utils/pools";

const Home: NextPage = () => {
  const poolQuery = usePoolCreatedQuery();

  const pool = React.useMemo(
    () =>
      (poolQuery?.data ?? null) != null ? parsePool(poolQuery.data) : null,
    [poolQuery?.data]
  );

  return (
    <div>
      <Head>
        <title>Kwenta Aelin Raise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Icons />
      </main>
    </div>
  );
};

export default Home;
